pub mod config;
pub mod crash_parser;
pub mod data;
pub mod db_manager;
mod errors;
pub mod file_drop;
pub mod instance_helpers;
pub mod migrations;
pub mod process_state;
pub mod sanitize;
pub mod sqlite;
pub mod version_tracking;
pub mod windows;
