//! Shared Minecraft game-options bundle.
//!
//! A bundle is a sparse set of values read from the source instance. Every
//! write patches only those values in the target `options.txt`; the rest of
//! the file stays owned by the instance or its pack. The per-instance
//! `applied` baseline makes exit capture directional and prevents a newly
//! re-followed instance from importing edits made while it was out.

use super::{Category, Preferences, SharedBundle, SharedValue, Snapshot};
use crate::game_options::catalog;
use crate::game_options_file::{self, Patch};
use crate::tasks::manager::{instance_play_conflict_key, TaskManager};
use crate::utils::db::get_config_conn;
use diesel::prelude::*;
use diesel::sql_types::Text;
use std::collections::{BTreeMap, BTreeSet};
use tauri::Manager;

static SERIAL: tokio::sync::Mutex<()> = tokio::sync::Mutex::const_new(());

const TABLE: &str = "shared_game_options";

/// Values which are generated by the game, owned by the pack, or tied to a
/// single session/device. They must never enter the shared game-options
/// bundle, even when a pack happens to include them.
const NEVER_SYNC: &[&str] = &[
    "version",
    "resourcePacks",
    "incompatibleResourcePacks",
    "soundDevice",
    "fullscreenResolution",
    "lastServer",
    "lastServerName",
    "chatFilterText",
    "realmsNotifications",
];

#[derive(QueryableByName)]
struct StateRow {
    #[diesel(sql_type = Text)]
    state: String,
}

fn load(conn: &mut SqliteConnection) -> Result<SharedBundle, String> {
    let query = format!("SELECT state FROM {TABLE} WHERE id = 1");
    diesel::sql_query(query)
        .get_result::<StateRow>(conn)
        .optional()
        .map_err(|error| error.to_string())?
        .map(|row| serde_json::from_str(&row.state).map_err(|error| error.to_string()))
        .unwrap_or_else(|| Ok(SharedBundle::default()))
}

fn store(conn: &mut SqliteConnection, shared: &SharedBundle) -> Result<(), String> {
    let state = serde_json::to_string(shared).map_err(|error| error.to_string())?;
    let query = format!(
        "INSERT INTO {TABLE} (id, state) VALUES (1, ?)
         ON CONFLICT(id) DO UPDATE SET state = excluded.state"
    );
    diesel::sql_query(query)
        .bind::<Text, _>(state)
        .execute(conn)
        .map_err(|error| error.to_string())?;
    Ok(())
}

fn never_sync(key: &str) -> bool {
    NEVER_SYNC.contains(&key)
}

/// `catalog::is_editable` rejects pack-owned values. The extra checks here
/// keep the broad catalog rule from admitting keybindings or session values.
fn is_syncable_key(key: &str) -> bool {
    !key.starts_with("key_") && !never_sync(key) && catalog::is_editable(key)
}

fn valid_extra(key: &str, value: &str) -> bool {
    !key.is_empty()
        && key.len() <= 4096
        && !key.contains(':')
        && !key.chars().any(char::is_control)
        && value.len() <= 64 * 1024
        && !value
            .chars()
            .any(|character| character == '\r' || character == '\n' || character == '\0')
}

/// Stable ids are supplied by the rich catalog when available. Until the
/// catalog bridge is present, physical names are also stable and keep old
/// stored rows readable. The catalog worker can replace this one function
/// without changing bundle or selection semantics.
fn id_for_key(key: &str) -> String {
    key.to_owned()
}

fn key_for_id<'a>(shared: &'a SharedBundle, id: &str) -> Option<&'a SharedValue> {
    shared.values.get(id)
}

fn selected(shared: &SharedBundle, preferences: &Preferences, id: &str) -> bool {
    preferences
        .selected_keys
        .as_ref()
        .is_none_or(|keys| keys.iter().any(|key| key == id || shared.values.get(key).is_some_and(|value| value.key == id)))
}

fn selected_values(
    shared: &SharedBundle,
    preferences: &Preferences,
    game_version: Option<&str>,
) -> BTreeMap<String, String> {
    shared
        .values
        .iter()
        .filter(|(id, value)| {
            selected(shared, preferences, id)
                && supported_for_version(&value.key, game_version)
        })
        .map(|(_, value)| (value.key.clone(), value.value.clone()))
        .collect()
}

/// The catalog owns exact version ranges. This fallback remains conservative
/// for the old catalog API; the rich catalog bridge can override it once
/// `SupportedSetting` exposes physical key ranges.
fn supported_for_version(_key: &str, _game_version: Option<&str>) -> bool {
    true
}

fn exposed_catalog() -> Vec<serde_json::Value> {
    // Keep the command response serializable without making the frontend
    // reconstruct catalog definitions. The richer catalog worker replaces the
    // implementation with its id/keys/range/editor/encoding metadata.
    catalog::CATALOG
        .iter()
        .map(|entry| {
            let (kind, min, max) = match entry.kind {
                catalog::ValueKind::Boolean => ("bool", None, None),
                catalog::ValueKind::Number { min, max } => ("number", Some(min), Some(max)),
                catalog::ValueKind::Text => ("text", None, None),
            };
            serde_json::json!({
                "id": entry.key,
                "keys": [entry.key],
                "since": serde_json::Value::Null,
                "until": serde_json::Value::Null,
                "category": entry.category,
                "labelId": entry.label_id,
                "editor": {"type": kind, "min": min, "max": max, "step": serde_json::Value::Null, "unit": serde_json::Value::Null},
                "encoding": kind,
            })
        })
        .collect()
}

pub(crate) fn populate(
    conn: &mut SqliteConnection,
    snapshot: &mut Snapshot,
) -> Result<(), String> {
    let shared = load(conn)?;
    snapshot.initialized = !shared.values.is_empty();
    snapshot.shared_values = shared.exposed_values();
    snapshot.catalog = exposed_catalog();
    Ok(())
}

fn current_game_version(instance: &crate::models::instance::Instance) -> Option<&str> {
    (!instance.minecraft_version.trim().is_empty()).then_some(instance.minecraft_version.as_str())
}

async fn idle(instance: &crate::models::instance::Instance) -> Result<(), String> {
    if instance.installation_status.as_deref() != Some("installed") {
        return Err("Instance is not installed and idle".into());
    }
    if piston_lib::game::launcher::is_instance_running(&instance.slug())
        .await
        .map_err(|error| error.to_string())?
    {
        return Err("Game is running; sync will resume after exit".into());
    }
    Ok(())
}

fn seed_values(values: &BTreeMap<String, String>, game_version: Option<&str>) -> SharedBundle {
    let mut shared = SharedBundle::default();
    for (key, value) in values {
        if !is_syncable_key(key)
            || !supported_for_version(key, game_version)
            || catalog::validate(key, value).is_err()
            || !valid_extra(key, value)
        {
            continue;
        }
        let id = id_for_key(key);
        shared.values.insert(
            id,
            SharedValue {
                key: key.clone(),
                value: value.clone(),
            },
        );
    }
    shared
}

fn resolve_change_id(shared: &SharedBundle, key: &str) -> Option<String> {
    if shared.values.contains_key(key) {
        return Some(key.to_owned());
    }
    shared
        .values
        .iter()
        .find(|(_, value)| value.key == key)
        .map(|(id, _)| id.clone())
}

fn apply_changes(shared: &mut SharedBundle, changes: BTreeMap<String, String>) -> Result<(), String> {
    for (raw_id, value) in changes {
        let id = resolve_change_id(shared, &raw_id)
            .ok_or_else(|| format!("Setting is not in the shared bundle: {raw_id}"))?;
        let entry = shared
            .values
            .get_mut(&id)
            .ok_or_else(|| format!("Setting is not in the shared bundle: {raw_id}"))?;
        if !is_syncable_key(&entry.key)
            || !valid_extra(&entry.key, &value)
            || catalog::validate(&entry.key, &value).is_err()
        {
            return Err(format!("Invalid shared value for {}", entry.key));
        }
        entry.value = value;
    }
    Ok(())
}

fn import_changes(shared: &mut SharedBundle, id: i32, current: &BTreeMap<String, String>) {
    let Some(baseline) = shared.applied.get(&id) else {
        // A newly-following instance is apply-only on its first pass.
        return;
    };
    for (setting_id, entry) in &mut shared.values {
        let Some(current_value) = current.get(&entry.key) else {
            continue;
        };
        if baseline
            .get(setting_id)
            .is_some_and(|previous| previous != current_value)
            && catalog::validate(&entry.key, current_value).is_ok()
            && valid_extra(&entry.key, current_value)
        {
            entry.value = current_value.clone();
        }
    }
}

fn selected_baseline(
    shared: &SharedBundle,
    preferences: &Preferences,
    game_version: Option<&str>,
    values: &BTreeMap<String, String>,
) -> BTreeMap<String, String> {
    shared
        .values
        .iter()
        .filter(|(id, value)| {
            selected(shared, preferences, id)
                && supported_for_version(&value.key, game_version)
                && values.contains_key(&value.key)
        })
        .map(|(id, value)| (id.clone(), values[&value.key].clone()))
        .collect()
}

/// The caller holds the per-instance play exclusion.
pub(crate) async fn apply_under_play_guard(id: i32) -> Result<(), String> {
    reconcile_one(id, true).await
}

/// A committed pack update is not a user edit. Reapply the selected bundle to
/// the pack's new options file and leave every other line as it arrived.
pub(crate) async fn restore_after_pack_update(id: i32) -> Result<(), String> {
    reconcile_one(id, false).await
}

async fn reconcile_one(id: i32, import: bool) -> Result<(), String> {
    let _serial = SERIAL.lock().await;
    let mut conn = get_config_conn().map_err(|error| error.to_string())?;
    let preferences = super::read(&mut conn, Category::GameOptions)?.preferences;
    if !preferences.enabled || !preferences.instance_ids.contains(&id) {
        return Ok(());
    }
    let mut shared = load(&mut conn)?;
    if shared.values.is_empty() {
        return Err("Choose a game-options source to initialize the shared bundle.".into());
    }
    let instance = crate::commands::instances::get_instance(id)?;
    idle(&instance).await?;
    let directory = crate::commands::game_options::directory(&instance)?;
    let current = game_options_file::load(&directory)?;
    if !current.exists {
        return Err("options.txt is missing; sync will resume after the game creates it.".into());
    }
    let game_version = current_game_version(&instance);

    if import {
        import_changes(&mut shared, id, &current.values);
        store(&mut conn, &shared)?;
    }

    let selected = selected_values(&shared, &preferences, game_version);
    if selected.is_empty() {
        return Ok(());
    }
    let saved = game_options_file::save(
        &directory,
        Patch {
            revision: current.revision,
            changes: selected.clone(),
        },
    )?;
    shared.applied.insert(
        id,
        selected_baseline(&shared, &preferences, game_version, &saved.values),
    );
    store(&mut conn, &shared)
}

async fn propagate(app: &tauri::AppHandle) -> Vec<String> {
    let ids = match get_config_conn()
        .map_err(|error| error.to_string())
        .and_then(|mut conn| super::read(&mut conn, Category::GameOptions))
    {
        Ok(snapshot) if snapshot.preferences.enabled => snapshot.preferences.instance_ids,
        Ok(_) => return Vec::new(),
        Err(error) => return vec![error],
    };
    let manager = app.state::<TaskManager>();
    let mut pending = Vec::new();
    for id in ids {
        let _play = manager
            .acquire_conflicts([instance_play_conflict_key(id)])
            .await;
        if let Err(error) = reconcile_one(id, true).await {
            let name = crate::commands::instances::get_instance(id)
                .map(|instance| instance.name)
                .unwrap_or_else(|_| id.to_string());
            pending.push(format!("{name}: {error}"));
        }
    }
    pending
}

pub(crate) async fn after_exit(app: tauri::AppHandle, slug: String) {
    let result = async {
        let instance = crate::commands::instances::get_instance_by_slug(slug)?;
        {
            let manager = app.state::<TaskManager>();
            let _play = manager
                .acquire_conflicts([instance_play_conflict_key(instance.id)])
                .await;
            reconcile_one(instance.id, true).await?;
        }
        for pending in propagate(&app).await {
            log::warn!("Game-options sync pending: {pending}");
        }
        Ok::<(), String>(())
    }
    .await;
    if let Err(error) = result {
        log::warn!("Game-options sync after exit: {error}");
    }
}

fn save_configuration(
    conn: &mut SqliteConnection,
    revision: i64,
    mut preferences: Preferences,
    mut shared: SharedBundle,
) -> Result<Snapshot, String> {
    if !preferences.enabled {
        shared.applied.clear();
    }
    preferences.source_instance_id = None;
    shared
        .applied
        .retain(|id, _| preferences.instance_ids.contains(id));
    for baseline in shared.applied.values_mut() {
        baseline.retain(|id, _| {
            preferences
                .selected_keys
                .as_ref()
                .is_none_or(|keys| keys.iter().any(|key| key == id || shared.values.get(key).is_some_and(|value| value.key == shared.values[id].key)))
        });
    }
    conn.transaction::<Snapshot, diesel::result::Error, _>(|conn| {
        let mut snapshot = super::save_preferences(conn, Category::GameOptions, revision, preferences)
            .map_err(|error| diesel::result::Error::QueryBuilderError(error.into()))?;
        store(conn, &shared)
            .map_err(|error| diesel::result::Error::QueryBuilderError(error.into()))?;
        snapshot.initialized = !shared.values.is_empty();
        snapshot.shared_values = shared.exposed_values();
        snapshot.catalog = exposed_catalog();
        Ok(snapshot)
    })
    .map_err(|error| error.to_string())
}

pub(crate) async fn configure(
    app: &tauri::AppHandle,
    revision: i64,
    previous: Preferences,
    mut preferences: Preferences,
    changes: BTreeMap<String, String>,
) -> Result<Snapshot, String> {
    let manager = app.state::<TaskManager>();
    let source_guard = preferences
        .source_instance_id
        .filter(|_| preferences.enabled)
        .map(|id| async move { manager.acquire_conflicts([instance_play_conflict_key(id)]).await });
    let source_guard = match source_guard {
        Some(future) => Some(future.await),
        None => None,
    };
    let mut conn = get_config_conn().map_err(|error| error.to_string())?;
    let mut shared = load(&mut conn)?;

    // Values and selection may only change while enabled. Membership is
    // checked by the outer command before entering this module.
    if (previous.enabled != preferences.enabled && !preferences.enabled)
        && (!changes.is_empty() || previous.selected_keys != preferences.selected_keys)
    {
        return Err("Enable game-options sync before editing shared options.".into());
    }
    if !changes.is_empty() && !preferences.enabled {
        return Err("Enable game-options sync before editing shared options.".into());
    }

    if preferences.enabled && shared.values.is_empty() {
        let source = preferences
            .source_instance_id
            .ok_or("Choose a source instance before enabling game-options sync.")?;
        let instance = crate::commands::instances::get_instance(source)?;
        idle(&instance).await?;
        let source_snapshot = game_options_file::load(
            &crate::commands::game_options::directory(&instance)?,
        )?;
        if !source_snapshot.exists {
            return Err("The source instance has no options.txt to seed yet.".into());
        }
        shared = seed_values(&source_snapshot.values, current_game_version(&instance));
        if shared.values.is_empty() {
            return Err("The source has no syncable game options.".into());
        }
        let baseline = shared
            .values
            .iter()
            .map(|(id, value)| (id.clone(), value.value.clone()))
            .collect();
        shared.applied.insert(source, baseline);
    }
    apply_changes(&mut shared, changes)?;
    let snapshot = save_configuration(&mut conn, revision, preferences, shared)?;
    drop(source_guard);

    let mut snapshot = snapshot;
    snapshot.pending = propagate(app).await;
    Ok(snapshot)
}

#[cfg(test)]
mod tests {
    use super::*;
    use diesel::connection::SimpleConnection;

    fn schema(conn: &mut SqliteConnection) {
        conn.batch_execute(include_str!(
            "../../migrations/config/2026-09-13-000000_settings_sync/up.sql"
        ))
        .unwrap();
        conn.batch_execute(include_str!(
            "../../migrations/config/2026-09-13-000001_shared_settings/up.sql"
        ))
        .unwrap();
    }

    #[test]
    fn seed_accepts_unknown_safe_options_and_rejects_keybinds_and_protected_values() {
        let values = BTreeMap::from([
            ("fov".into(), "0".into()),
            ("renderDistance".into(), "12".into()),
            ("mod.customSetting".into(), "true".into()),
            ("key_key.forward".into(), "key.keyboard.w".into()),
            ("version".into(), "4903".into()),
        ]);
        let shared = seed_values(&values, Some("1.21.1"));
        assert!(shared.values.contains_key("fov"));
        assert!(shared.values.contains_key("renderDistance"));
        assert!(shared.values.contains_key("mod.customSetting"));
        assert!(!shared.values.contains_key("key_key.forward"));
        assert!(!shared.values.contains_key("version"));
    }

    #[test]
    fn readd_prunes_baseline_and_never_imports_local_while_out() {
        let mut conn = SqliteConnection::establish(":memory:").unwrap();
        schema(&mut conn);
        let mut shared = SharedBundle {
            values: BTreeMap::from([(
                "renderDistance".into(),
                SharedValue {
                    key: "renderDistance".into(),
                    value: "12".into(),
                },
            )]),
            applied: BTreeMap::from([(
                1,
                BTreeMap::from([("renderDistance".into(), "12".into())]),
            )]),
        };
        let prefs = Preferences {
            enabled: true,
            instance_ids: vec![1],
            selected_keys: Some(vec!["renderDistance".into()]),
            ..Default::default()
        };
        save_configuration(&mut conn, 0, prefs.clone(), shared.clone()).unwrap();
        shared = load(&mut conn).unwrap();
        shared.applied.clear(); // The instance is out and is added again.
        import_changes(
            &mut shared,
            1,
            &BTreeMap::from([("renderDistance".into(), "32".into())]),
        );
        assert_eq!(shared.values["renderDistance"].value, "12");
    }

    #[test]
    fn selected_game_options_never_include_keybinds() {
        let shared = SharedBundle {
            values: BTreeMap::from([
                (
                    "fov".into(),
                    SharedValue {
                        key: "fov".into(),
                        value: "0".into(),
                    },
                ),
                (
                    "key_key.forward".into(),
                    SharedValue {
                        key: "key_key.forward".into(),
                        value: "17".into(),
                    },
                ),
            ]),
            ..Default::default()
        };
        let values = selected_values(
            &shared,
            &Preferences::default(),
            Some("1.21.1"),
        );
        assert_eq!(values.keys().collect::<BTreeSet<_>>(), BTreeSet::from([&"fov".into()]));
    }
}
