/**
 * Pack-aware skin embedder.
 *
 * Modes:
 *   bun scripts/embed-skins.ts --retag
 *     Re-assign pack_id / pack_name on existing crates/piston-lib/src/api/embedded_skins.rs
 *     using scripts/skin-packs.catalog.json (no PNG rewrite).
 *
 *   bun scripts/embed-skins.ts [SKIN_DIR]
 *     Build embedded_skins.rs from a skins root. Layout:
 *       SKIN_DIR/
 *         defaults/slim/*.png
 *         defaults/wide/*.png
 *         <pack_id>/*.png          (or <pack_id>.zip containing PNGs)
 *         <pack_id>/slim + wide    (optional dual variants)
 *     SKIN_DIR may also be set via env.
 */
import { spawnSync } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const catalogPath = path.join(__dirname, "skin-packs.catalog.json");
const outputFile = path.join(repoRoot, "crates/piston-lib/src/api/embedded_skins.rs");

type PackKind = "defaults" | "event_pack";

interface PackDef {
	id: string;
	name: string;
	kind: PackKind;
	order: number;
	keys?: string[];
	keyPrefixes?: string[];
	keyIncludes?: string[];
	fallback?: boolean;
}

interface Catalog {
	packs: PackDef[];
	displayNames?: Record<string, string>;
}

interface SkinEntry {
	key: string;
	name: string;
	packId: string;
	packName: string;
	/** Raw base64 payload (no data: prefix). */
	slimData?: string;
	classicData?: string;
	slimMime?: string;
	classicMime?: string;
}

function loadCatalog(): Catalog {
	return JSON.parse(fs.readFileSync(catalogPath, "utf8")) as Catalog;
}

function resolvePack(catalog: Catalog, textureKey: string): PackDef {
	const normalized = textureKey.toLowerCase();
	const ranked = [...catalog.packs].sort((a, b) => a.order - b.order);

	for (const pack of ranked) {
		if (pack.fallback) continue;
		if (pack.keys?.some((k) => k.toLowerCase() === normalized)) return pack;
	}
	for (const pack of ranked) {
		if (pack.fallback) continue;
		if (pack.keyPrefixes?.some((p) => normalized.startsWith(p.toLowerCase()))) {
			return pack;
		}
	}
	for (const pack of ranked) {
		if (pack.fallback) continue;
		if (pack.keyIncludes?.some((p) => normalized.includes(p.toLowerCase()))) {
			return pack;
		}
	}

	const fallback =
		ranked.find((p) => p.fallback) ??
		ranked.find((p) => p.id === "other_events");
	if (!fallback) {
		throw new Error("Catalog is missing a fallback pack");
	}
	return fallback;
}

function escapeRustString(value: string): string {
	return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function textureOption(data?: string, mime = "image/png"): string {
	if (!data) return "None";
	return `Some(Arc::from("data:${mime};base64,${data}"))`;
}

function resolveDisplayName(
	catalog: Catalog,
	key: string,
	fallback: string,
): string {
	const override = catalog.displayNames?.[key];
	if (override) return override;
	return fallback;
}

function writeEmbeddedSkins(skins: SkinEntry[], catalog: Catalog): void {
	const sorted = [...skins].sort((a, b) => {
		if (a.packId !== b.packId) return a.packId.localeCompare(b.packId);
		return a.key.localeCompare(b.key);
	});

	let rust = `// Automatically generated by scripts/embed-skins.ts
// Do not edit by hand — re-run: bun scripts/embed-skins.ts --retag
// or: bun scripts/embed-skins.ts /path/to/skins-root
use crate::models::common::{Skin, SkinSource};
use once_cell::sync::Lazy;
use std::sync::Arc;

pub static EMBEDDED_SKINS: Lazy<Vec<Skin>> = Lazy::new(|| {
    vec![
`;

	for (const skin of sorted) {
		const displayName = resolveDisplayName(catalog, skin.key, skin.name);
		const slim = textureOption(skin.slimData, skin.slimMime);
		let classic = textureOption(skin.classicData, skin.classicMime);
		if (!skin.slimData && !skin.classicData) {
			classic = "None";
		}

		rust += `        Skin {
            texture_key: Arc::from("${escapeRustString(skin.key)}"),
            name: Some(Arc::from("${escapeRustString(displayName)}")),
            source: SkinSource::Default {
                pack_id: Some(Arc::from("${escapeRustString(skin.packId)}")),
                pack_name: Some(Arc::from("${escapeRustString(skin.packName)}")),
                category: Some(Arc::from("${escapeRustString(skin.packName)}")),
                slim_texture: ${slim},
                classic_texture: ${classic},
            },
        },\n`;
	}

	rust += `    ]
});
`;

	fs.mkdirSync(path.dirname(outputFile), { recursive: true });
	fs.writeFileSync(outputFile, rust);

	const byPack = new Map<string, number>();
	for (const skin of sorted) {
		byPack.set(skin.packId, (byPack.get(skin.packId) ?? 0) + 1);
	}

	console.log(`Wrote ${sorted.length} skins → ${path.relative(repoRoot, outputFile)}`);
	for (const [packId, count] of [...byPack.entries()].sort()) {
		console.log(`  ${packId}: ${count}`);
	}
}

function parseDataUri(value: string): { mime: string; data: string } {
	const cleaned = value.replace(/\s+/g, "");
	const match = cleaned.match(/^data:([^;]+);base64,(.+)$/);
	if (match) {
		return { mime: match[1], data: match[2] };
	}
	return { mime: "image/png", data: cleaned };
}

function retagExisting(catalog: Catalog): void {
	const source = fs.readFileSync(outputFile, "utf8");
	// Match Skin blocks, allowing multiline Arc::from("...") string literals.
	const blockRe =
		/Skin\s*\{[\s\S]*?texture_key:\s*Arc::from\("([^"]+)"\),[\s\S]*?name:\s*Some\(Arc::from\("([^"]*)"\)\),[\s\S]*?source:\s*SkinSource::Default\s*\{([\s\S]*?)\n\s*\},?/g;

	const skins: SkinEntry[] = [];
	let match: RegExpExecArray | null;
	while ((match = blockRe.exec(source)) !== null) {
		const key = match[1];
		const name = match[2];
		const body = match[3];

		const slim = extractTexturePayload(body, "slim_texture");
		const classic = extractTexturePayload(body, "classic_texture");

		const pack = resolvePack(catalog, key);
		skins.push({
			key,
			name,
			packId: pack.id,
			packName: pack.name,
			slimData: slim?.data,
			classicData: classic?.data,
			slimMime: slim?.mime,
			classicMime: classic?.mime,
		});
	}

	if (skins.length === 0) {
		throw new Error(`No Skin entries parsed from ${outputFile}`);
	}

	const expected = new Set(catalog.packs.map((p) => p.id));
	const present = new Set(skins.map((s) => s.packId));
	const missing = [...expected].filter(
		(id) =>
			!present.has(id) &&
			id !== "other_events" &&
			catalog.packs.find((p) => p.id === id)?.kind === "event_pack",
	);
	if (missing.length > 0) {
		console.warn(`Missing packs (add zips under SKIN_DIR later): ${missing.join(", ")}`);
	}

	writeEmbeddedSkins(skins, catalog);
}

function extractTexturePayload(
	body: string,
	field: string,
): { mime: string; data: string } | undefined {
	const someRe = new RegExp(
		`${field}:\\s*Some\\(Arc::from\\("([\\s\\S]*?)"\\)\\)`,
	);
	const match = body.match(someRe);
	if (!match) return undefined;

	const parsed = parseDataUri(match[1]);
	if (!parsed.data) return undefined;
	return parsed;
}

function isJunkPath(name: string): boolean {
	return (
		name.startsWith("._") ||
		name === "__MACOSX" ||
		name.startsWith(".DS_Store")
	);
}

function listImageFiles(dir: string): string[] {
	if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];
	return fs
		.readdirSync(dir)
		.filter((f) => !isJunkPath(f) && /\.(png|jpe?g|webp)$/i.test(f))
		.map((f) => path.join(dir, f));
}

function listImagesRecursive(dir: string): string[] {
	if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];
	const out: string[] = [];
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (isJunkPath(entry.name)) continue;
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			out.push(...listImagesRecursive(full));
		} else if (/\.(png|jpe?g|webp)$/i.test(entry.name)) {
			out.push(full);
		}
	}
	return out;
}

function mimeFromPath(filePath: string): string {
	const ext = path.extname(filePath).toLowerCase();
	if (ext === ".webp") return "image/webp";
	if (ext === ".jpg" || ext === ".jpeg") return "image/jpeg";
	return "image/png";
}

function unzipToTemp(zipPath: string): string {
	const temp = fs.mkdtempSync(path.join(os.tmpdir(), "vesta-skin-pack-"));
	const result = spawnSync("unzip", ["-o", "-q", zipPath, "-d", temp], {
		encoding: "utf8",
	});
	if (result.status !== 0) {
		throw new Error(
			`Failed to unzip ${zipPath}: ${result.stderr || result.stdout || "unknown error"}`,
		);
	}
	return temp;
}

function displayNameFromFile(filePath: string): string {
	const base = path.basename(filePath, path.extname(filePath));
	return base
		.replace(/[_-]+/g, " ")
		.replace(/\s+/g, " ")
		.trim()
		.replace(/\b\w/g, (c) => c.toUpperCase());
}

function textureKeyFromFile(filePath: string, pack: PackDef): string {
	const base = path
		.basename(filePath, path.extname(filePath))
		.toLowerCase()
		.replace(/ /g, "_");
	if (pack.kind === "defaults") return base;
	// Filenames that already end in _event are stable keys (from extract/retag).
	if (base.endsWith("_event")) return base;
	// Namespace short names from official zips to avoid cross-pack collisions
	// (e.g. Valorie exists in both Dungeons packs).
	return `${pack.id}_${base}_event`;
}

function ingestPackDir(
	pack: PackDef,
	packDir: string,
	into: Map<string, SkinEntry>,
): void {
	const slimDir = path.join(packDir, "slim");
	const wideDir = path.join(packDir, "wide");
	const hasVariants =
		fs.existsSync(slimDir) || fs.existsSync(wideDir);

	if (pack.kind === "defaults" || hasVariants) {
		for (const file of listImageFiles(slimDir)) {
			const key = textureKeyFromFile(file, pack);
			const existing = into.get(key) ?? {
				key,
				name: displayNameFromFile(file),
				packId: pack.id,
				packName: pack.name,
			};
			existing.slimData = fs.readFileSync(file).toString("base64");
			existing.slimMime = mimeFromPath(file);
			existing.packId = pack.id;
			existing.packName = pack.name;
			into.set(key, existing);
		}
		for (const file of listImageFiles(wideDir)) {
			const key = textureKeyFromFile(file, pack);
			const existing = into.get(key) ?? {
				key,
				name: displayNameFromFile(file),
				packId: pack.id,
				packName: pack.name,
			};
			existing.classicData = fs.readFileSync(file).toString("base64");
			existing.classicMime = mimeFromPath(file);
			existing.packId = pack.id;
			existing.packName = pack.name;
			into.set(key, existing);
		}
	}

	// Flat / nested images (event packs, or defaults without slim/wide)
	const skipDirs = new Set(["slim", "wide"]);
	for (const entry of fs.readdirSync(packDir, { withFileTypes: true })) {
		const full = path.join(packDir, entry.name);
		if (entry.isDirectory()) {
			if (skipDirs.has(entry.name)) continue;
			for (const file of listImagesRecursive(full)) {
				addClassicImage(pack, file, into);
			}
		} else if (/\.(png|jpe?g|webp)$/i.test(entry.name)) {
			addClassicImage(pack, full, into);
		}
	}
}

function addClassicImage(
	pack: PackDef,
	file: string,
	into: Map<string, SkinEntry>,
): void {
	const key = textureKeyFromFile(file, pack);
	const mime = mimeFromPath(file);
	const existing = into.get(key);
	if (existing?.slimData || existing?.classicData) {
		// Prefer explicit slim/wide variants when both exist
		if (!existing.classicData) {
			existing.classicData = fs.readFileSync(file).toString("base64");
			existing.classicMime = mime;
		}
		return;
	}
	into.set(key, {
		key,
		name: displayNameFromFile(file),
		packId: pack.id,
		packName: pack.name,
		classicData: fs.readFileSync(file).toString("base64"),
		classicMime: mime,
	});
}

function buildFromSkinDir(skinDir: string, catalog: Catalog): void {
	const byKey = new Map<string, SkinEntry>();
	const tempDirs: string[] = [];

	try {
		const entries = fs.readdirSync(skinDir, { withFileTypes: true });
		const packById = new Map(catalog.packs.map((p) => [p.id, p]));

		// Legacy layout support: slim/ + wide/ + root event PNGs
		const legacySlim = path.join(skinDir, "slim");
		const legacyWide = path.join(skinDir, "wide");
		if (fs.existsSync(legacySlim) || fs.existsSync(legacyWide)) {
			const defaults = packById.get("defaults");
			if (defaults) ingestPackDir(defaults, skinDir, byKey);
		}

		for (const entry of entries) {
			const full = path.join(skinDir, entry.name);
			if (entry.isFile() && entry.name.toLowerCase().endsWith(".zip")) {
				const packId = path.basename(entry.name, path.extname(entry.name));
				const pack =
					packById.get(packId) ??
					resolvePack(catalog, `${packId}_event`);
				const extracted = unzipToTemp(full);
				tempDirs.push(extracted);
				ingestPackDir(pack, extracted, byKey);
				continue;
			}

			if (!entry.isDirectory()) {
				// Legacy: root-level event images
				if (/\.(png|jpe?g|webp)$/i.test(entry.name)) {
					const key = textureKeyFromFile(full, {
						id: "other_events",
						name: "Other Event Skins",
						kind: "event_pack",
						order: 1000,
					});
					const pack = resolvePack(catalog, key);
					addClassicImage(pack, full, byKey);
				}
				continue;
			}

			if (entry.name === "slim" || entry.name === "wide") continue;

			const pack =
				packById.get(entry.name) ??
				resolvePack(catalog, `${entry.name}_event`);
			ingestPackDir(pack, full, byKey);
		}

		if (byKey.size === 0) {
			throw new Error(`No PNG skins found under ${skinDir}`);
		}

		const expected = catalog.packs
			.filter((p) => p.kind === "event_pack" && !p.fallback)
			.map((p) => p.id);
		const present = new Set([...byKey.values()].map((s) => s.packId));
		const missing = expected.filter((id) => !present.has(id));
		if (missing.length > 0) {
			console.warn(`Missing packs in SKIN_DIR: ${missing.join(", ")}`);
		}

		writeEmbeddedSkins([...byKey.values()], catalog);
	} finally {
		for (const dir of tempDirs) {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	}
}

function main(): void {
	const catalog = loadCatalog();
	const args = process.argv.slice(2);

	if (args.includes("--retag") || args.includes("--from-embedded")) {
		retagExisting(catalog);
		return;
	}

	const skinDirArg = args.find((a) => !a.startsWith("-"));
	const skinDirEnv = process.env.SKIN_DIR;
	const skinDir =
		skinDirArg && skinDirArg.trim().length > 0
			? path.resolve(skinDirArg)
			: skinDirEnv && skinDirEnv.trim().length > 0
				? path.resolve(skinDirEnv)
				: "";

	if (!skinDir || !fs.existsSync(skinDir) || !fs.statSync(skinDir).isDirectory()) {
		throw new Error(
			"Provide SKIN_DIR / a skins directory, or pass --retag to re-pack existing embeds.\n" +
				"  bun scripts/embed-skins.ts --retag\n" +
				"  bun scripts/embed-skins.ts /path/to/skins-root",
		);
	}

	buildFromSkinDir(skinDir, catalog);
}

main();
