import fs from "fs";
import path from "path";

const skinDir = "skin folder";
const outputDir = "crates/piston-lib/src/api";
const outputFile = path.join(outputDir, "embedded_skins.rs");

function getFiles(dir: string): string[] {
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir)
        .filter(f => f.endsWith(".png"))
        .map(f => path.join(dir, f));
}

const allSkins: Record<string, { 
    name: string, 
    key: string,
    slimData?: string, 
    classicData?: string, 
    eventData?: string,
    category: string 
}> = {};

// Process Slim
for (const file of getFiles(path.join(skinDir, "slim"))) {
    const name = path.basename(file, ".png");
    const key = name.toLowerCase().replace(/ /g, "_");
    allSkins[key] = { 
        name, 
        key,
        slimData: fs.readFileSync(file).toString("base64"),
        category: "Default"
    };
}

// Process Wide (Classic)
for (const file of getFiles(path.join(skinDir, "wide"))) {
    const name = path.basename(file, ".png");
    const key = name.toLowerCase().replace(/ /g, "_");
    if (allSkins[key]) {
        allSkins[key].classicData = fs.readFileSync(file).toString("base64");
    } else {
        allSkins[key] = {
            name,
            key,
            classicData: fs.readFileSync(file).toString("base64"),
            category: "Default"
        };
    }
}

// Process Events (Root)
for (const file of getFiles(skinDir)) {
    const name = path.basename(file, ".png");
    const key = name.toLowerCase().replace(/ /g, "_") + "_event";
    const data = fs.readFileSync(file).toString("base64");
    allSkins[key] = {
        name,
        key,
        eventData: data,
        category: "Mojang Events"
    };
}

let rustContent = `// Automatically generated by scripts/embed-skins.ts
use crate::models::common::{Skin, MinecraftSkinVariant, SkinSource};
use once_cell::sync::Lazy;
use std::sync::Arc;

pub static EMBEDDED_SKINS: Lazy<Vec<Skin>> = Lazy::new(|| {
    vec![
`;

for (const skin of Object.values(allSkins)) {
    let slimTexture = skin.slimData ? `Some(Arc::from("data:image/png;base64,${skin.slimData}"))` : "None";
    let classicTexture = skin.classicData ? `Some(Arc::from("data:image/png;base64,${skin.classicData}"))` : "None";

    // Handle skins that don't have explicit classic or slim data (e.g. event skins)
    // If neither exists, assume the primary event/base data is classic.
    if (!skin.slimData && !skin.classicData && skin.eventData) {
        classicTexture = `Some(Arc::from("data:image/png;base64,${skin.eventData}"))`;
    }

    rustContent += `        Skin {
            texture_key: Arc::from("${skin.key}"),
            name: Some(Arc::from("${skin.name}")),
            source: SkinSource::Default {
                category: Some(Arc::from("${skin.category}")),
                slim_texture: ${slimTexture},
                classic_texture: ${classicTexture},
            },
        },\n`;
}

rustContent += `    ]
});
`;

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}
fs.writeFileSync(outputFile, rustContent);
console.log("Generated dual-variant skins.");
